apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: microservices
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: app-deploy
